-- MySQL Script generated by MySQL Workbench
-- Sun Jan 30 14:52:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Airline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Airline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Airline` DEFAULT CHARACTER SET utf8 ;
USE `Airline` ;

-- -----------------------------------------------------
-- Table `Airline`.`destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`destinations` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `airport` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`statuses` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`manufacturers` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `manufacturer_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`airplanes` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(64) NOT NULL,
  `business_seat` INT NOT NULL,
  `economy_seat` INT NOT NULL,
  `maximum_takeoff_weight` INT NOT NULL,
  `flight_range` INT NOT NULL,
  `cruising_speed` INT NOT NULL,
  `maximum_flight_height` INT NOT NULL,
  `manufacturers_id` BIGINT(19) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_airplane_models_manufacturers1_idx` (`manufacturers_id` ASC) VISIBLE,
  CONSTRAINT `fk_airplane_models_manufacturers1`
    FOREIGN KEY (`manufacturers_id`)
    REFERENCES `Airline`.`manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`flights` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `flight_number` VARCHAR(64) NOT NULL,
  `departure_date` DATE NULL,
  `departure_time` TIME NULL,
  `destinations_id` BIGINT(19) NOT NULL,
  `statuses_id` BIGINT(19) NOT NULL,
  `airplanes_id` BIGINT(19) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flights_destinations1_idx` (`destinations_id` ASC) VISIBLE,
  INDEX `fk_flights_statuses1_idx` (`statuses_id` ASC) VISIBLE,
  INDEX `fk_flights_airplanes1_idx` (`airplanes_id` ASC) VISIBLE,
  CONSTRAINT `fk_flights_destinations1`
    FOREIGN KEY (`destinations_id`)
    REFERENCES `Airline`.`destinations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_statuses1`
    FOREIGN KEY (`statuses_id`)
    REFERENCES `Airline`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_airplanes1`
    FOREIGN KEY (`airplanes_id`)
    REFERENCES `Airline`.`airplanes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`roles` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`ranks` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `rank_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`users` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `surname` VARCHAR(64) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `role_id` BIGINT(19) NOT NULL,
  `rank_id` BIGINT(19) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_rank1_idx` (`rank_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `Airline`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rank1`
    FOREIGN KEY (`rank_id`)
    REFERENCES `Airline`.`ranks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`airplanes_has_ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`airplanes_has_ranks` (
  `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `rank_count` INT NOT NULL,
  `airplanes_id` BIGINT(19) NOT NULL,
  `ranks_id` BIGINT(19) NOT NULL,
  INDEX `fk_airplanes_has_ranks_ranks1_idx` (`ranks_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_airplanes_has_ranks_airplanes1_idx` (`airplanes_id` ASC) VISIBLE,
  CONSTRAINT `fk_airplanes_has_ranks_ranks1`
    FOREIGN KEY (`ranks_id`)
    REFERENCES `Airline`.`ranks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airplanes_has_ranks_airplanes1`
    FOREIGN KEY (`airplanes_id`)
    REFERENCES `Airline`.`airplanes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airline`.`brigades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airline`.`brigades` (
  `flights_id` BIGINT(19) NOT NULL,
  `users_id` BIGINT(19) NOT NULL,
  PRIMARY KEY (`flights_id`, `users_id`),
  INDEX `fk_flights_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_flights_has_users_flights1_idx` (`flights_id` ASC) VISIBLE,
  CONSTRAINT `fk_flights_has_users_flights1`
    FOREIGN KEY (`flights_id`)
    REFERENCES `Airline`.`flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Airline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
